### ISSUE TITLE
install through pip and fandango path

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/fandango#7]
Hello Sergi,
I tried to install fandango on debian 8 through `pip install fandango`.
I got the following content for `.local/lib/python2.7/site-packages/fandango`:
```
arrays.py      device        excepts.py      log.py       tango
arrays.pyc     devslist.py   excepts.pyc     log.pyc      test
callbacks.py   devslist.pyc  functional.py   objects.py   threads.py
callbacks.pyc  dicts.py      functional.pyc  objects.pyc  threads.pyc
CHANGES        dicts.pyc     __init__.py     qt.py        VERSION
db.py          doc.py        __init__.pyc    qt.pyc       web.py
db.pyc         doc.pyc       interface       scripts      web.pyc
debug.py       dynamic.py    linos.py        servers.py   widget
debug.pyc      dynamic.pyc   linos.pyc       servers.pyc
```
It is a bit strange since I do not have any fandango script. 
Is it the normal directory content?

**Comment by sergirubio** [comment]
In principle it should have been installed the fandango script under /usr/bin/

I have a Debian 8 machine and I'll try to replicate it

**Comment by sergirubio** [comment]
Hi PhiLAL, I know it has been a long time
Could you try again with fandango 13.7 that I just uploaded to pipy? Thanks

**Comment by PhilLAL** [comment]
Hi Sergi, 
I did not test with debian8/tango8, but on debian9/tango9 I have the same otput.
I precise that on tango9, I can call fandango (see for example https://github.com/tango-controls/SimulatorDS/issues/4).

**Comment by sergirubio** [comment]
Hi PhiLAL,
I've just try it on a Debian9 docker and fandango script was installed under /usr/local/bin
Can you test it?
Sergi

**Comment by PhilLAL** [comment]
Hi Sergi,
thank you for this test.

I get back a VM on debian 9 with TANGO basic installation.
I then installed upgraded it (sudo apt upgrade) and installed python-pip (sudo apt update && sudo apt install python-pip) and at last installed fandango (pip install fandango, without sudo).
/usr/local/bin is empty, and I found a ~/.local/lib/python2.7/site-packages/fandango/ directory. 

Did you install it through sudo?

**Comment by sergirubio** [comment]
yes, I installed fandango using sudo; it installed the script in 
/usr/local/bin but not in site-packages

I'm going to add it to the manifest to see if it solves the problem

**Comment by PhilLAL** [comment]
Ok, thank you Sergi.
By any chance, is there a way to install fandango without root rights for users or virtual environment?

**Comment by sergirubio** [comment]
Hi, after updating the manifest it worked for me, now I have fandango and tango_servers scripts available in a user virtualenv.

Could you try again?

**Comment by PhilLAL** [comment]
Hi Sergi,
thank you for coming back to me.

I tested again in a VM and I got this
```
$ ls .local/lib/python2.7/site-packages/fandango
arrays.py      debug.pyc     dynamic.py      interface    qt.pyc       VERSION
arrays.pyc     device        dynamic.pyc     linos.py     scripts      web.py
callbacks.py   devslist.py   excepts.py      linos.pyc    servers.py   web.pyc
callbacks.pyc  devslist.pyc  excepts.pyc     log.py       servers.pyc  widget
CHANGES        dicts.py      functional.py   log.pyc      tango
db.py          dicts.pyc     functional.pyc  objects.py   test
db.pyc         doc.py        __init__.py     objects.pyc  threads.py
debug.py       doc.pyc       __init__.pyc    qt.py        threads.pyc
```
This seems exactly the same content than in first post. I'm a bit confused since it was several months I did not installed fandango. I wonder if I am not awaiting the script to be in the wrong directory, or perhaps did I forget some step during installation...

**Comment by sergirubio** [comment]
Hi, 
I've installed it in a docker and the scripts are under .local/bin
$ pip install --user fandango       
Collecting fandango
  Downloading https://files.pythonhosted.org/packages/a1/57/a172b3ab79a836d1a7903eed2ec550636fde0a2eda521ada41f3193629c0/fandango-14.3.0.tar.gz (273kB)
    100% |################################| 276kB 1.4MB/s 
Building wheels for collected packages: fandango
  Running setup.py bdist_wheel for fandango ... done
  Stored in directory: /home/tester/.cache/pip/wheels/f1/8b/56/4920d9bc1e00bfb1f1f0639331b4d05d67fb69721a31134a12
Successfully built fandango
Installing collected packages: fandango
Successfully installed fandango-14.3.0
$ find -name fandango
./.local/bin/fandango
./.local/lib/python2.7/site-packages/fandango
$ dir .local/bin 
CopyCatDS  DynamicDS  FolderDS  WorkerDS  csv2tango  ctds  fandango  folder-gui  sardanact  tango2csv  tango2json  tango_cleanup  tango_host  tango_monitor  tango_property  tango_servers

**Comment by PhilLAL** [comment]
Hello,
thank you for giving the instructions. I remember I did not use `--user` option so this was perhaps due to this

I followed following steps to install:
```
apt update python-pip
pip install --user fandango
```
and then I find the files, everything is OK. 
Thank you.
