### ISSUE TITLE
using dot into device names

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/fandango#9]
Hi,
as just discussed, I encounter an issue while trying to generating a simulator from a DS named with a dot : 
` ./gen_simulation.py export RDP1.txt RDP1_attributes.pck`

The content of file RDP1.txt is the following:
`er/ca/rac05-elr.01-rdp1`

The original DS is currently running on a computer so it works.

I imagine a temporary solution would be to use alias or to temporarly install the DS without a dot (but all our nomenclature is based on dot).

**Comment by PhilLAL** [comment]
Hi, just a reminder.
FYI, I try in parallel to test alias but without success currently.

**Comment by sergirubio** [comment]
Hi Philippe,

I'm still on medical leave, but coming  back tomorrow

Thanks for the reminder and I'll try to provide you a solution

Sergi

**Comment by PhilLAL** [comment]
Thanks, and cheers

**Comment by PhilLAL** [comment]
Hi, for information, I created an alias with success, but when launching `fandango -l find_devices "redpitaya" > RDP1.txt`
I got an empty file.

**Comment by sergirubio** [comment]
Hi PhiLAL,

Sorry for the late feedback, I'll try to give it a look

Sergi

**Comment by PhilLAL** [comment]
Thanks, let me know if I can give you any input.

**Comment by PhilLAL** [comment]
Hi Sergi, I will be off for 2 next weeks, but if you have some time to give or insights to give on this, it would be great.:)

**Comment by sergirubio** [comment]
Hi Philippe,

I just pushed a fix to the develop branch, I'm working on other fixes but this should solve the export problem.

Sorry for the late commit,

Sergi

**Comment by PhilLAL** [comment]
Hi Sergi, thank you for your fix, I will test it soon.
Hope you had a nice summer. :)

**Comment by PhilLAL** [comment]
Hi Sergi,
I installed the new version through `pip install [local fandango repo]` and I tested this new version under TANGO9 on debian 9

To test it, I launched `fandango -l find_devices "er/*/*" > essai/redpitaya.txt`.
The content of generated file `essai/redpitaya.txt` seems correct:
```
er/ca/rac05-elr.01-rdp1
```
However, when generating PCK file, the content is not correct:
```
$ cd ~/SimulatorDS/essai
$ ~/SimulatorDS/gen_simulation.py export redpitaya.txt redpitaya.pck 
Welcome to the generic simulation script
--------------------------------------------------------------------------------
export_attributes from:(['redpitaya.txt'], 'redpitaya.pck')
devices to export: []
['export'] done
$ cat essai/redpitaya.pck 
ccollections
defaultdict
p0
(cfandango.objects
Struct
p1
tp2
Rp3
.
```

I also tested it on TANGO 8/Debian 8 a slightly different DS with same result : 
`fandango -l find_devices "ER/CA/RAC.05-ELR.01-RDP.01" >  ER__CA__RAC_05-ELR_01-RDP_01.pck`
then 
```
$ gen_simulation.py export ER__CA__RAC_05-ELR_01-RDP_01.pck RedPitaya.pck
Welcome to the generic simulation script
--------------------------------------------------------------------------------
export_attributes from:(['ER__CA__RAC_05-ELR_01-RDP_01.pck'], 'RedPitaya.pck')
devices to export: []
['export'] done
```
The generated file has exactly the same content.

**Comment by sergirubio** [comment]
I just updated pip with latest release 13.9

Please, try again

**Comment by PhilLAL** [comment]
Seems much more complete, thank you for this update Sergi!
